stages:
  - lint
  - format
  - type_check
  - test
  - security

variables:
  PYTHON_VERSION: "3.12"

default:
  image: python:${PYTHON_VERSION}-slim

  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install ruff black mypy pytest bandit
    - pip install -r requirements.txt

ruff_lint:
  stage: lint
  script:
    -python -m  ruff check .

black_format_check:
  stage: format
  script:
    - python -m black --check .

mypy_type_check:
  stage: type_check
  script:
    -python -m mypy .

pytest_tests:
  stage: test
  script:
    - pytest

bandit_scan:
  stage: security
  script:
    - bandit -r .